feat: migration guide
SigNoz/signoz.io-old pull request #1037
Opened 2023-08-16 03:21 UTC by nityanandagohain

Fixes https://github.com/SigNoz/signoz/issues/2594

2023-08-16 04:51 UTC, ankit01-oss commented
@nityanandagohain let me know if this can be merged.

2023-08-16 05:06 UTC, nityanandagohain commented
@ankit01-oss we can merge this only after new release is done. I have the merge access, will merge once done.

2023-08-16 05:16 UTC, ankit01-oss commented
sure.

2023-08-23 16:20 UTC, prashant-shahi requested changes

2023-08-23 16:20 UTC, prashant-shahi commented on docs/operate/migration/upgrade-0.27.md
> +In the SigNoz version `>=0.27` i.e. SigNoz chart version `>=0.19.0`, [clickhouse][1]
New chart version will be `0.23.x`.

```suggestion
In the SigNoz version `>=0.27` i.e. SigNoz chart version `>=0.23.0`, [clickhouse][1]
```

2023-08-23 16:20 UTC, prashant-shahi commented on docs/operate/migration/upgrade-0.27.md
> +Follow the platform specific instructions to upgrade to 0.10 and above.
```suggestion
Follow the platform specific instructions to upgrade to 0.27 and above.
```

2023-08-23 16:25 UTC, prashant-shahi approved these changes

2023-08-23 16:25 UTC, merged