Add cloud instructions in k8s infra metrics docs and otel binary usag…
SigNoz/signoz.io-old pull request #1054
Opened 2023-08-22 09:48 UTC by ankit01-oss

…e docs

2023-08-22 11:52 UTC, prashant-shahi requested changes
reviewed and left comments

2023-08-22 11:52 UTC, prashant-shahi commented on docs/tutorial/kubernetes-infra-metrics.md
> +  --set otelCollectorEndpoint=ingest.signoz.io:4317 \
```suggestion
  --set otelCollectorEndpoint=ingest.{region}.signoz.cloud:443 \
```

Best to include the table below after this command:

| Region | Endpoint |
| ------- | --------- |
| US | `ingest.us.signoz.io:443` |
| IN | `ingest.in.signoz.io:443` |
| EU | `ingest.eu.signoz.io:443` |

2023-08-22 11:52 UTC, prashant-shahi commented on docs/tutorial/kubernetes-infra-metrics.md
> +		value: service.name=APPLICATION_NAME,k8s.pod.ip=$(K8S_POD_IP),k8s.pod.uid=$(K8S_POD_UID)
indentation not right

2023-08-22 11:52 UTC, prashant-shahi commented on docs/tutorial/kubernetes-infra-metrics.md
> +  applications ⇒ otel-collectors in your infra ⇒ SigNoz cloud
not sure if this should be included like this.

Proper pictorial representation would be better than the text with arrows.

2023-08-22 11:52 UTC, prashant-shahi commented on docs/tutorial/kubernetes-infra-metrics.md
> +  - In cases of some SDKs, you would have to include `http://` or `https://` prefix for `OTEL_EXPORTER_OTLP_ENDPOINT`
```suggestion
  - In cases of some SDKs, you would have to include `https://` prefix for `OTEL_EXPORTER_OTLP_ENDPOINT`
```

2023-08-22 11:52 UTC, prashant-shahi commented on docs/tutorial/opentelemetry-binary-usage.md
> +        mute_process_name_error: true
Add all the following to supress most of the unwanted errors while scraping process metrics.

```suggestion
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
```

2023-08-22 11:52 UTC, prashant-shahi commented on docs/tutorial/opentelemetry-binary-usage.md
> +    endpoint: "ingest.signoz.io:4317"
```suggestion
    endpoint: "ingest.{region}.signoz.io:443"
```

2023-08-22 11:52 UTC, prashant-shahi commented on docs/tutorial/opentelemetry-binary-usage.md
> +Application Instrumentation → Otel-Binary Agent in Same VM → SigNoz Saas
same as previous comment.

Proper pictorial representation would be better than the text with arrows.

2023-08-22 11:52 UTC, prashant-shahi commented on docs/tutorial/opentelemetry-binary-usage.md
> + ```
not sure if this whole section should be part of this page.

Best to break it into multiple small tutorial pages but link them here.

@srikanthccv  what do you think about this?

2023-08-22 11:57 UTC, prashant-shahi commented on docs/tutorial/opentelemetry-binary-usage.md
> +        mute_process_name_error: true
applicable in both Cloud and Self-Host

2023-08-23 07:59 UTC, ankit01-oss commented on docs/tutorial/opentelemetry-binary-usage.md
> +        mute_process_name_error: true
@prashant-shahi for self-host, we don't have any instructions for `config.yaml` file.

2023-08-23 08:04 UTC, ankit01-oss commented on docs/tutorial/opentelemetry-binary-usage.md
> + ```
ok commented out for now

2023-08-23 08:04 UTC, ankit01-oss commented on docs/tutorial/kubernetes-infra-metrics.md
> +  applications ⇒ otel-collectors in your infra ⇒ SigNoz cloud
ok

2023-08-23 08:05 UTC, merged