feat: added docs for VM Hostmetrics
SigNoz/signoz.io-old pull request #1208
Opened 2023-10-13 13:54 UTC by Calm-Rock

Added docs for HostMetrics and added a section under Infrastructure Monitoring

2023-10-16 12:59 UTC, ankit01-oss commented on docs/userguide/hostmetrics.md
> +You can choose from the two options below
```suggestion
You can choose from the two options below.
```

2023-10-16 12:59 UTC, ankit01-oss commented on docs/userguide/hostmetrics.md
> +A full list of supported hostmetrics can be found <a href = "https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/README.md#getting-started" rel="n
```suggestion
A full list of supported hostmetrics can be found <a href = "https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/README.md#getting-started" rel="noopener noreferrer nofollow" target="_blank" >here</a>.
```

2023-10-16 12:59 UTC, ankit01-oss commented on docs/userguide/hostmetrics.md
> +A receiver serves as the entry point for data into the OpenTelemetry Collector. The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM, and is in
```suggestion
A receiver serves as the entry point for data into the OpenTelemetry Collector. The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM, and is intended to be used when the collector is deployed as an agent.
```

@srikanthccv can you review the paragraph here? Can we say receiver is an entry point or is it just a config. 

@Calm-Rock I am not sure about the second line - `The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM`. If the receiver generates the metrics, what does it scrap? I think the receiver just scrapes metrics, there is no generation involved. @srikanthccv can confirm.

2023-10-16 12:59 UTC, ankit01-oss commented on docs/userguide/hostmetrics.md
> +Click on **Configure** button at top right corner to change the name, add/remove tags, edit description, and add more variables to your dashboard. These things can be edited before uploading the JSON
```suggestion
These things can be edited before uploading the JSON file or from the dashboard itself.
```

Not sure if this line is required. I think if we are enabling an easier process from our dashboard, explaining that should be enough.

2023-10-16 12:59 UTC, ankit01-oss commented on docs/userguide/hostmetrics.md
> +To explore more dashboard functionalities, check out the  <a href = "https://signoz.io/docs/userguide/manage-dashboards-and-panels/" rel="noopener noreferrer nofollow" target="_blank" >Dashboard Sect
```suggestion
To explore more dashboard functionalities, check out the  <a href = "https://signoz.io/docs/userguide/manage-dashboards-and-panels/" rel="noopener noreferrer nofollow" target="_blank" >Dashboard Section</a>.
```

2023-10-16 12:59 UTC, ankit01-oss commented on docs/userguide/hostmetrics.md
> +There two ways in which the Self-Host version of SigNoz can be configured :
```suggestion
There two ways in which the Self-Host version of SigNoz can be configured:

- SigNoz is installed on the same VM as your application
- SigNoz is installed on a different VM
```

2023-10-16 13:00 UTC, ankit01-oss commented
@prashant-shahi would be great if you also review this before it goes live.

2023-10-17 08:57 UTC, srikanthccv commented on docs/userguide/hostmetrics.md
> +A receiver serves as the entry point for data into the OpenTelemetry Collector. The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM, and is in
Yes, you are correct. It doesn't generate any metric on its own. The scraper receiver is a kind of receiver that periodically tries to fetch the metrics from some source (which generates the metrics). The host metrics receiver scrapes the metrics from the host machine.

2023-10-19 03:47 UTC, prashant-shahi requested changes

2023-10-19 03:47 UTC, prashant-shahi commented on docs/userguide/hostmetrics.md
> +The **Host Metrics dashboard** consists of charts for monitoring instance metrics and is designed as a generic dashboard with a hostname variable. You can access detailed information on common host m
```suggestion
The **Host Metrics dashboard** consists of charts for monitoring instance metrics and is designed as a generic dashboard with a hostname variable. You can access detailed information on common host system metrics such as:
```

Also, we will also need to add a section for Kubernetes. In which case we will have to either also include `kubernetes nodes` next to instance or replace `instance` with `host system`.

2023-10-19 03:47 UTC, prashant-shahi commented on docs/userguide/hostmetrics.md
> +A receiver serves as the entry point for data into the OpenTelemetry Collector. The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM, and is in
`The Host Metrics receiver generates metrics about the host system scraped from various sources` is correct.
But not `like your VM`. Here various sources are not VMs but cross-platform libraries with scraper functions used to retrieve information on running processes and system utilization.

2023-10-19 03:47 UTC, prashant-shahi commented on docs/userguide/hostmetrics.md
> +**Step 3** : Import hostmetrics json file to SigNoz Cloud
```suggestion
**Step 3** : Import hostmetrics JSON file to SigNoz Cloud
```

2023-10-19 03:47 UTC, prashant-shahi commented on docs/userguide/hostmetrics.md
> +A receiver serves as the entry point for data into the OpenTelemetry Collector. The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM, and is in
same as above

2023-10-19 03:47 UTC, prashant-shahi commented on docs/userguide/hostmetrics.md
> +When SigNoz is running on the same VM as the Host, it automatically starts collecting the Hostmetrics data because the hostmetrics receiver is enabled by default in the OTel collector that comes bund
```suggestion
When SigNoz is running on the same VM as the Host, it automatically starts collecting
the Hostmetrics data because the hostmetrics receiver is enabled by default in the
OTel collector configuration that comes bundled with SigNoz.
```

@Calm-Rock Breaking long lines helps in review. One line should not exceed 100 chars, while 70-80 chars being ideal per line.

2023-10-19 03:47 UTC, prashant-shahi commented on docs/userguide/hostmetrics.md
> +**Step 3** : Import hostmetrics json file to SigNoz Cloud
can you also update other usage of `json` with `JSON`?

2023-10-19 04:22 UTC, ankit01-oss commented
<img width="902" alt="Screenshot 2023-10-19 at 9 53 10 AM" src="https://github.com/SigNoz/signoz.io/assets/83692067/a8e3fb71-cb6f-46dd-adc2-c212353422ff">

@Calm-Rock can we make this in dark mode?

2023-10-19 09:31 UTC, srikanthccv commented on docs/userguide/hostmetrics.md
> +A receiver serves as the entry point for data into the OpenTelemetry Collector. The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM, and is in
Your interpretation of what metric generation seems to be different. The metrics are generated by kernel modules and are written to particular files. The host metrics simply read them and create OTLP-compatible data. This applies to other scrapers as well. For instance, A Postgres DB server is the actual process that generates the metrics and saves them to some monitoring DB which is read by the collector and creates OTLP data.

2023-10-19 09:37 UTC, srikanthccv commented on docs/userguide/hostmetrics.md
> +A receiver serves as the entry point for data into the OpenTelemetry Collector. The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM, and is in
In the context of host metrics, the source here is not a cross-platform library but a file that contains the info example `/sys/block/sda/size`, `/proc/...` etc. Whatever the cross-platform thing you mention is an library that makes it easier to read these files on different operating systems.

2023-10-19 09:38 UTC, srikanthccv commented on docs/userguide/hostmetrics.md
> +A receiver serves as the entry point for data into the OpenTelemetry Collector. The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM, and is in
The source for different scrapers is different, for some, it's some files, and for others, it's some table in DB. And third-party library only helps read such data.

2023-10-19 09:48 UTC, srikanthccv commented on docs/userguide/hostmetrics.md
> +A receiver serves as the entry point for data into the OpenTelemetry Collector. The Host Metrics receiver generates metrics about the host system scraped from various sources, like your VM, and is in
@ankit01-oss saying host metrics receiver generates metrics is as accurate as saying file log receiver generates logs. Neither of them generates anything on their own. They simply collect the data generated by other processes and format them in an OTLP-compatible format.

2023-10-20 11:46 UTC, merged