docs(ecs-infra): ✨ EC2/External tutorial using Daemon Service
SigNoz/signoz.io-old pull request #1251
Opened 2023-10-30 16:03 UTC by prashant-shahi

Signed-off-by: Prashant Shahi <prashant@signoz.io>

2023-10-31 11:56 UTC, nityanandagohain requested changes

2023-10-31 11:56 UTC, nityanandagohain commented on docs/shared/ecs-infra/daemon-service-template-ec2.md
> +*daemon-template.yaml*
Add as step 1 and mention we are going to use this file in step 3

2023-10-31 11:56 UTC, nityanandagohain commented on docs/shared/ecs-infra/daemon-service-config-intro.md
> +### Step 2: Create SigNoz OtelCollector Config
Add image

2023-10-31 11:57 UTC, nityanandagohain commented on docs/shared/ecs-infra/daemon-service-set-up-verify.md
> +To configure the daemon service, you need to run the following command with the proper values for the parameters.
Ask user to replace the values of clyster name and ecs region explicitly.

2023-10-31 11:58 UTC, nityanandagohain commented on docs/shared/ecs-infra/daemon-service-set-up-verify.md
> +aws cloudformation create-stack --stack-name AOCECS-daemon-${CLUSTER_NAME}-${REGION} \
seperate into two blocks as one needs replacement and the other doesn't.

2023-10-31 12:12 UTC, nityanandagohain commented on docs/tutorial/ecs-infra.md
> +<DSTemplateExternal />
Add that fargate is not support yet

2023-10-31 12:13 UTC, nityanandagohain commented on docs/tutorial/ecs-infra.md
> +
select the type of ecs cluster

2023-10-31 12:36 UTC, nityanandagohain commented
Add docs for cleanup as well.

2023-11-01 14:23 UTC, Calm-Rock commented on docs/shared/ecs-infra/daemon-service-config-cloud.md
> +- Include SigNoz ingestion key in place of `<signoz-ingestion-token>`
```suggestion
- Include SigNoz ingestion key in place of `<signoz-ingestion-token>`
```
We can remove this bullet point as we are mentioning about `SIGNOZ_INGESTION_KEY` in the next bullet point.

2023-11-01 14:23 UTC, Calm-Rock commented on docs/shared/ecs-infra/daemon-service-config-cloud.md
> +- Replace `SIGNOZ_INGESTION_KEY` with the ingestion token of your SigNoz Cloud account
```suggestion
- Replace `SIGNOZ_INGESTION_KEY` with the ingestion key of your SigNoz Cloud account
```

2023-11-01 14:23 UTC, Calm-Rock commented on docs/shared/ecs-infra/daemon-service-config-cloud.md
> +- After successful set up, feel free to remove `logging` exporter if it gets too noisy.
Below this line we should mention

You can find the `SigNoz Ingestion Key` and `region` details in the invitation email or the Settings Tab of your SigNoz cloud UI.

2023-11-01 14:23 UTC, Calm-Rock commented on docs/shared/ecs-infra/daemon-service-set-up-verify.md
> +```
Please mention about what these variables represent
- `REGION`
- `CLUSTER_NAME`
- `COMMAND`
- `SIGNOZ_CONFIG_CONTENT`
- `SIGNOZ_CONFIG`

2023-11-01 14:23 UTC, Calm-Rock commented on docs/shared/ecs-infra/daemon-service-set-up-verify.md
> +```
Here as well
What does `REGION` represent ? Is it the AWS region or the SigNoz Cloud Region ?
Create a bullet point explaining this.

Also include a bullet point for what `CLUSTER_NAME` Is here as well.

2023-11-01 14:23 UTC, Calm-Rock commented on docs/shared/ecs-infra/daemon-service-send-data-intro.md
> +This step can also include adding the OpenTelemetry SDK as well as the
Can we add this as `:::note  :::` admonition and also hyperlink `OpenTelemetry SDK` to a relevant link for instrumentation using OpenTelemetry SDK ?

2023-11-01 14:23 UTC, Calm-Rock commented on docs/shared/ecs-infra/daemon-service-send-data-ec2.md
> +        "export OTEL_EXPORTER_OTLP_ENDPOINT=\"http://$(curl http://169.254.169.254/latest/meta-data/local-ipv4):4317\"; <Application Startup Commands>"
What is `<Application Startup Commands>`?
Can you add a bullet point explaining it?

2023-11-01 14:23 UTC, Calm-Rock commented on docs/shared/ecs-infra/daemon-service-send-data-end.md
> +SigNoz {props.name} page and you should see your application in the services list.
Can you mention which section of SigNoz Cloud will the user see the data ?
SigNoz Cloud logs/Metrics/Services whichever is relevant.

2023-11-01 14:23 UTC, Calm-Rock commented on docs/shared/ecs-infra/daemon-service-send-data-external.md
> +    				'export OTEL_EXPORTER_OTLP_ENDPOINT="http://$(curl "http://169.254.169.254/computeMetadata/v1/instance/network-interfaces/0/ip?recursive=true&alt=text" -H "Metadata-Flavor: Google"):4317"; <A
What is `<Application Startup Commands>`?
Can you add a bullet point explaining it everywhere it is mentioned?

2023-11-02 16:25 UTC, nityanandagohain commented on docs/shared/ecs-infra/daemon-service-template-ec2.md
> +          Image: 'signoz/signoz-otel-collector:0.79.12'
change it to 0.79.7

2023-11-03 06:02 UTC, prashant-shahi commented on docs/shared/ecs-infra/daemon-service-set-up-verify.md
> +```
Only `REGION` and `CLUSTER_NAME` are needed.

Adding them in an info block

2023-11-03 06:03 UTC, prashant-shahi commented on docs/shared/ecs-infra/daemon-service-set-up-verify.md
> +```
I think one info block in the beginning should suffice for this.

If required, we can come back and update this.

2023-11-03 15:23 UTC, merged