chore: added docs for collecting tomcat access and gc logs
SigNoz/signoz.io-old pull request #1725
Opened 2024-05-13 09:35 UTC by nityanandagohain

Fixes https://github.com/SigNoz/engineering-pod/issues/1274

2024-05-22 03:57 UTC, Calm-Rock requested changes

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +---
@nityanandagohain, please create a folder named 

`send-logs-to-signoz` under [logs-management](https://github.com/SigNoz/signoz.io/tree/main/docs/logs-management) and put this docs inside that folder. We won't be using user guide for new docs.

@ankit01-oss can you please check the link and confirm if this seems okay.

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +id: collecting_tomcat_access_and_gc_logs
```suggestion
id: collect-tomcat-access-and-garbage-collector-logs
```

We are using `-` instead of `_` for all the new docs.

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +This guide provides detailed instructions on configuring the OpenTelemetry Collector to read read Tomcat Server Access and Garbage Collector logs and push them to SigNoz, enabling you to analyze them
```suggestion
This documentation provides detailed instructions about configuring the OpenTelemetry Collector to read Tomcat Server Access and Garbage Collector logs and push them to SigNoz, enabling you to analyze them effectively.
```

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +
We can add a H2 here and put the sample logs as H3 under this heading.

## Sample Log

Here is how the Tomcat Access logs and Garbage Collector logs look like:

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +## Sample Access Log
```suggestion
### Sample Access Log
```

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +## Sample Garbage Collector log
```suggestion
### Sample Garbage Collector log
```

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +## Collect Tomcat Access and Garbage Collector Logs in SigNoz Cloud
```suggestion
## Collect Logs in SigNoz Cloud
```

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +## Collecting Tomcat Access and Garbage Collector Logs in self-hosted SigNoz
```suggestion
## Collect logs in self-hosted SigNoz
```

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +You can install OpenTelemetry collector as an agent on your Virtual Machine by following this [guide](https://signoz.io/docs/tutorial/opentelemetry-binary-usage-in-virtual-machine/).
```suggestion
You can install OpenTelemetry collector (OTel collector) as an agent by following this [guide](https://signoz.io/docs/tutorial/opentelemetry-binary-usage-in-virtual-machine/). 
```

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +Add the filelog reciever to `otel-collector-config.yaml` which is present inside `deploy/docker/clickhouse-setup` directory in your self-hosted SigNoz setup. The configuratoin below tells the collect
```suggestion
Add the filelog reciever to `otel-collector-config.yaml` which is present inside `deploy/docker/clickhouse-setup` directory in your self-hosted SigNoz setup. The configuration below tells the collector where to find your log file and how to start processing it.
```

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +
```suggestion
<br> </br>
```

To make some space between the two images.

2024-05-22 03:57 UTC, Calm-Rock commented on docs/userguide/collecting_tomcat_access_and_gc_logs.md
> +
```suggestion
<br> </br>
```

To make some space between the two images

2024-05-23 10:24 UTC, nityanandagohain commented
@Calm-Rock please check now

2024-05-30 04:38 UTC, Calm-Rock approved these changes

2024-05-30 04:38 UTC, merged