docs(k8s-infra): update kubernetes infra monitoring docs
SigNoz/signoz.io-old pull request #1737
Opened 2024-05-16 09:38 UTC by prashant-shahi

Signed-off-by: Prashant Shahi <prashant@signoz.io>

2024-05-21 16:16 UTC, prashant-shahi commented
We had multiple users ask us about instructions to disable either/both of the metrics and logs collection.

This PR will address such cases.

2024-05-22 03:04 UTC, Calm-Rock requested changes

2024-05-22 03:04 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
```suggestion
We use the `K8s-infra` helm chart for collecting Kubernetes Metrics and logs.

```

Add this line before explaining what the helm chart does.

2024-05-22 03:04 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
> +Depending on the choice of your region for SigNoz cloud, the ingest endpoint will vary according to this table.
```suggestion
Depending on the choice of your region for SigNoz cloud, the ingestion endpoint will vary according to this table.
```

2024-05-22 03:04 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
Remove this sentence

2024-05-22 03:48 UTC, srikanthccv submitted a review, later dismissed
LGTM, Thanks.

2024-05-22 03:48 UTC, srikanthccv commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
Why?

2024-05-22 03:49 UTC, srikanthccv commented on docs/tutorial/kubernetes-infra-metrics.md
I think the following line does the better job than this sentence.

2024-05-22 03:56 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
`Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster), you have to provide the address to send data from the above receivers.`

I think the user will be told in the instructions that they need to change the address based on whether they select SigNoz Cloud or Self-Host, right ? Am I missing some context here ?

 Writing this sentence without providing any context will create confusion for the user.

2024-05-22 03:56 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
Which line ?

2024-05-22 04:06 UTC, srikanthccv commented on docs/tutorial/kubernetes-infra-metrics.md
The line below explains what it does with bullet points. The bulleted list with details is helpful than the generic message "collecting Kubernetes Metrics and logs"

`K8s-Infra` helm chart mainly does the following:

2024-05-22 04:08 UTC, srikanthccv commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
I don't understand what you are asking about. What creates confusion and how?

2024-05-22 04:14 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
Yes, I agree with you. I'm not saying to remove the bullet points section. I just suggested to add a small sentence above this line **`K8s-Infra` helm chart mainly does the following:**. 

Since we don't mention about using K8s infra helm chart anywhere before this line.

2024-05-22 04:15 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
`you have to provide the address to send data from the above receivers.`

What address?

2024-05-22 04:27 UTC, srikanthccv commented on docs/tutorial/kubernetes-infra-metrics.md
I believe it is redundant and doesn't add anything.

2024-05-22 04:28 UTC, srikanthccv commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
The endpoint address where SigNoz is running (whether it's cloud or self hosted or anything else)

2024-05-22 04:33 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
That's included in the instructions that the user will follow, right? 

Mentioning it at the top without any context isn't helpful.

2024-05-22 04:37 UTC, srikanthccv commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
So if context is missing the solution is to remove the line or make it more explicit what the address is referring to?

2024-05-22 04:38 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
We use the `K8s-infra` helm chart for collecting Kubernetes Metrics and logs.

`K8s-Infra` helm chart mainly does the following:

- Tails and parses logs generated by containers in Kubernetes cluster and sends to SigNoz
- Collects kubelet metrics and host metrics from each nodes of the Kubernetes cluster
- Collects cluster-level metrics from the Kubernetes API server
- Acts as a gateway to send any incoming OTLP telemetry data to SigNoz OtelCollector

I think adding a line mentioning about K8s-Infra helm chart will be used would be better than directly jumping to explaining what K8s-infra chart does

2024-05-22 04:40 UTC, srikanthccv commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
I am just trying to understand if there is a methodological steps to decide what to remove and what to add because in one instance above you suggested including a line that doesn't add anything and here suggestion was to remove a line.

2024-05-22 04:48 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
The above comment was part of the **Overview** section of the docs. The overview section will give a broader overview of what the docs does - so mentioning clear context there is a good practice.

This is the instructions section of the docs where the user is expected to follow certain steps, and under each step, we will have explanation for that step. If something, for example, the address needs to be changed, it's better to mention it in that particular step. 

I will work on a Notion Doc which will clearly state the what's and what not's of documentation.

2024-05-22 04:51 UTC, srikanthccv commented on docs/tutorial/kubernetes-infra-metrics.md
The first two paragraphs are just about that (i.e. explain metrics and logs are collected). How does adding this line add anything?

2024-05-22 04:56 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
We don't mention anything about using K8s-Infra helm chart in the first to paragraph and then we directly jump to explaining what K8s-Infra helm chart does.

2024-05-22 15:00 UTC, prashant-shahi commented on docs/tutorial/kubernetes-infra-metrics.md
I agree with @srikanthccv here. The suggested one liner does not explains all what the `k8s-infra` helm chart does.
And it would be redundant to that of bullet points.

2024-05-22 15:05 UTC, prashant-shahi commented on docs/tutorial/kubernetes-infra-metrics.md
>  Based on how you are running SigNoz (e.g. SigNoz Cloud, in an independent VM or Kubernetes cluster),
> - Acts as a gateway to send any incoming OTLP telemetry data to SigNoz OtelCollector

From the technical perspective, this line is important as it says that they send any OTLP data to the otel-agent running in the same host as that of source pod, and it would be forwarded to SigNoz.

We could improve this line to say `SigNoz Cloud/Self-hosted` instead of `SigNoz OtelCollector`, if that's something you do not think is right.

> I will work on a Notion Doc which will clearly state the what's and what not's of documentation.

That would surely be helpful. We could have an internal session on the good todos for documentation.

2024-05-23 04:32 UTC, Calm-Rock commented on docs/tutorial/kubernetes-infra-metrics.md
Like I mentioned above, I'm not saying to remove the bullet pointers. I'm just saying to add this one line before the bullet points.

2024-05-23 05:02 UTC, prashant-shahi commented on docs/tutorial/kubernetes-infra-metrics.md
I feel like we are conversing in circle here with nothing new to add.

This particular change is just a re-order of an existing bullet section.

Can you address these points in another PR instead?

2024-05-23 05:03 UTC, Calm-Rock approved these changes

2024-05-23 05:07 UTC, merged

2024-05-23 05:11 UTC, prashant-shahi commented
@Calm-Rock @srikanthccv Thanks for the review 🙏