first draft for migration-0.10 doc
SigNoz/signoz.io-old pull request #416
Opened 2022-07-14 10:08 UTC by makeavish

2022-07-14 10:12 UTC, prashant-shahi requested changes

2022-07-14 10:12 UTC, prashant-shahi commented on docs/operate/migration/upgrade-0.10.md
> +  -it -d signoz/migrate:0.8 -host=clickhouse -port=9000
replace `0.8` to `0.10`

2022-07-14 10:12 UTC, prashant-shahi commented on docs/operate/migration/upgrade-0.10.md
> +kubectl -n platform run -i -t signoz_migrate --image=signoz/migrate:0.8 \
replace `0.8` to `0.10`

2022-07-14 10:12 UTC, prashant-shahi commented on docs/operate/migration/upgrade-0.10.md
> +### Kubernetes
Can you include docker swarm instructions as well before K8s one?

Steps will be slightly different in swarm.
- either expose the clickhouse ports and run the similar command via port exposed in host machine
- copy the binary asset inside the clickhouse or query-service container and run the migration script with appropriate arguments

2022-07-15 16:55 UTC, makeavish commented
@prashant-shahi Please add docker swarm docs and test migration on k8s before merging

2022-07-16 02:26 UTC, closed without merging

2022-07-16 02:27 UTC, pranay01 commented
merged updated PR  - https://github.com/SigNoz/signoz.io/pull/432
Closing this