Updated docs for feature flags
SigNoz/signoz.io-old pull request #637
Opened 2022-11-16 13:37 UTC by ankit01-oss

2022-11-16 13:57 UTC, makeavish requested changes

2022-11-16 13:57 UTC, makeavish commented on docs/operate/feature-flags.md
> +You can disable these features by adding configs to OTel Collector and Query Service.
We should highlight this line:

> To toggle features, configs have to be added on both OTel Collector and Query Service

2022-11-16 13:57 UTC, makeavish commented on docs/operate/feature-flags.md
> +- `DURATION_SORT_FEATURE`: When this feature is enabled, then SigNoz creates a projection over table to optimize sorting spans/traces by timestamp at cost of increasing storage by 40-50% of `signoz_i
add 'table' at the end of the line to complete the sentence

2022-11-16 13:57 UTC, makeavish commented on docs/operate/feature-flags.md
> +- `TIMESTAMP_SORT_FEATURE`: When this feature is enabled, then SigNoz creates a materialized view table to optimize sorting spans/traces by timestamp at cost of increasing storage by 40-50% of `signo
add 'table' at the end of the line to complete the sentence

2022-11-21 11:09 UTC, ankit01-oss commented on docs/operate/feature-flags.md
> +- `DURATION_SORT_FEATURE`: When this feature is enabled, then SigNoz creates a projection over table to optimize sorting spans/traces by timestamp at cost of increasing storage by 40-50% of `signoz_i
Incorporated.

2022-11-21 11:24 UTC, merged

2022-11-21 11:24 UTC, ankit01-oss commented
@makeavish merged.