created self-host page #858
SigNoz/signoz.io-old pull request #860
Opened 2023-03-29 15:31 UTC by akshay-bharadva

### issue : #858 

- created self-host signup page

2023-03-30 06:33 UTC, ankit01-oss commented
Hi @akshay-bharadva , Can you also include some basic validation checks in the form?

2023-04-03 13:57 UTC, palashgdev requested changes

2023-04-03 13:57 UTC, palashgdev commented on src/css/custom.css
> +.email-subscribe{
can you please make a separate CSS file in which you can import this one

2023-04-03 13:57 UTC, palashgdev commented on src/css/custom.css
> +  color: #000000;
can we make sure we use design tokens which are already configured

2023-04-03 13:57 UTC, palashgdev commented on src/css/custom.css
> +  font-size: 16px;
use rem everywhere

2023-04-03 13:57 UTC, palashgdev commented on src/pages/self-host.js
> +                    <input
can we have common input as we are repeating outself

2023-04-03 13:57 UTC, palashgdev commented on src/pages/self-host.js
> +                      {...register("email", {
let's declare constant for same

2023-04-03 13:57 UTC, palashgdev commented on package.json
> +    "react-hook-form": "^7.43.8",
```suggestion
    "react-hook-form": "7.43.8",
```

2023-04-03 14:02 UTC, closed without merging