Pricing refactoring
SigNoz/signoz.io-old pull request #873
Opened 2023-04-11 16:23 UTC by akshay-bharadva

- [x] created styles - module
- [x] js -> ts refactor
- [x] style refactor
- [x] added standard media breakpoint
- [x] create variables of common styles
- [ ] refactor svgs
- [x] use rem instead of px

2023-04-12 04:20 UTC, palashgdev requested changes

2023-04-12 04:20 UTC, palashgdev commented on src/modules/community-edition/styles.module.css
>    letter-spacing: -0.015em;
rem?

2023-04-12 04:20 UTC, palashgdev commented on src/modules/community-edition/index.tsx
> +            [styles.readDocsBtn]: true,
there is no need of cx if there is no condition

2023-04-12 04:20 UTC, palashgdev commented on src/modules/community-edition/styles.module.css
>    letter-spacing: -0.015em;
same here

2023-04-12 04:20 UTC, palashgdev commented on src/modules/community-edition/styles.module.css
>    letter-spacing: -0.015em;
here also

2023-04-12 04:20 UTC, palashgdev commented on src/modules/community-edition/styles.module.css
> +  padding-right: 10px !important;
rem

2023-04-12 04:20 UTC, palashgdev commented on src/modules/community-edition/styles.module.css
> +  margin: 6px;
here also

2023-04-12 04:20 UTC, palashgdev commented on src/modules/community-edition/styles.module.css
> +@media (max-width: 768px) {
token for 768?

2023-04-12 04:20 UTC, palashgdev commented on src/modules/try-signoz-cta/index.tsx
> +            className={clsx({
same here also

2023-04-12 04:20 UTC, palashgdev commented on src/modules/why-opentelemetry/styles.module.css
> +  height: 120px;
rem

2023-04-12 04:20 UTC, palashgdev commented on src/pages/pricing/index.js
> +            [styles.pricingContainer]: true,
here also

2023-04-12 04:20 UTC, palashgdev commented on src/pages/pricing/index.js
> +                className={clsx({
check every where

2023-04-12 04:20 UTC, palashgdev commented on src/pages/pricing/styles.module.css
> +  border: 0.5px solid #464646 !important;
token for color ?

2023-04-19 09:10 UTC, palashgdev requested changes

2023-04-19 09:10 UTC, palashgdev commented on src/css/custom.css
> +  --ifm-mobile-start: 320px;
please remove this one if we are not using this one

2023-04-19 09:10 UTC, palashgdev commented on src/modules/signup-form/index.tsx
> +        className={`${styles.submitBtn}`}
```suggestion
        className={styles.submitBtn}
```

2023-04-19 09:10 UTC, palashgdev commented on src/pages/pricing/index.js
> +ReactGA.initialize("UA-152867655-1");
why we are initialising here ?

2023-04-19 16:52 UTC, akshay-bharadva commented on src/pages/pricing/index.js
> +ReactGA.initialize("UA-152867655-1");
@palashgdev
This change will be removed once I create form for `get-cloud` and `self-hosted` pages

2023-04-20 03:49 UTC, merged