`prettier` and `eslint` configuration
SigNoz/signoz.io-old pull request #880
Opened 2023-04-14 14:47 UTC by akshay-bharadva

- configurations
  - [ ] prettier
    - [ ] husky
  - [ ] eslint

2023-04-19 09:02 UTC, palashgdev requested changes

2023-04-19 09:02 UTC, palashgdev commented on package-lock.json
why this file is here ? @akshay-bharadva

2023-04-19 09:02 UTC, palashgdev commented on package.json
> +    "eslint-config-standard-with-typescript": "^34.0.1",
please make all the package exact

2023-04-19 09:02 UTC, palashgdev commented on .husky/pre-commit
> +npx lint-staged
use yarn here

2023-04-27 17:35 UTC, akshay-bharadva commented on package.json
> +    "eslint-config-standard-with-typescript": "^34.0.1",
made package version exact

2023-04-27 17:36 UTC, akshay-bharadva commented on .husky/pre-commit
> +npx lint-staged
https://typicode.github.io/husky/#/?id=install-1

2023-08-10 07:53 UTC, closed without merging